config/routes.rb
InventoryControl::Application.routes.draw do
  resources :sales
  resources :customers
  resources :products
  resources :brands
  resources :purchases
  match '/:controller(/:action(/:id))'
end

app/models/brand.rb
class Brand < ActiveRecord::Base
  has_many :products
end

app/models/client.rb
class Client < ActiveRecord::Base
  has_many :sales
end

app/models/customer.rb
class Customer < ActiveRecord::Base
  has_many :sales
end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :brand
  
  has_many :sale_orders
  has_many :sales, :through => :sale_orders
  
  has_many :purchase_orders
  has_many :purchases, :through => :purchase_orders

  named_scope :with_brand, { :joins => :brand }
  named_scope :stock_alert, { :conditions => "stock_ammount = stock_minimum" }
end

app/models/purchase.rb
class Purchase < ActiveRecord::Base
  has_many :purchase_orders
  has_many :products, :through => :purchase_orders
end

app/models/purchase_order.rb
class PurchaseOrder < ActiveRecord::Base
  belongs_to :purchase
  belongs_to :product
end

app/models/sale.rb
class Sale < ActiveRecord::Base
  belongs_to :customer
  
  has_many :sale_orders
  has_many :products, :through => :sale_orders
end

app/models/sale_order.rb
class SaleOrder < ActiveRecord::Base
  belongs_to :sale
  belongs_to :product
end

app/controllers/brands_controller.rb
class BrandsController < InheritedResources::Base
  respond_to :html
end

app/controllers/clients_controller.rb
class ClientsController < InheritedResources::Base
  respond_to :html
end

app/controllers/customers_controller.rb
class CustomersController < InheritedResources::Base
  respond_to :html
end

app/controllers/products_controller.rb
class ProductsController < InheritedResources::Base
  respond_to :html

  def index
    index! { @products = Product.with_brand }
  end
end

app/controllers/purchases_controller.rb
class PurchasesController < InheritedResources::Base
  respond_to :html
end

app/controllers/sales_controller.rb
class SalesController < InheritedResources::Base
  respond_to :html
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    @content_for_title = page_title.to_s
    @show_title = show_title
  end
  
  def show_title?
    @show_title
  end
  
  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end
  
  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/purchases_helper.rb
module PurchasesHelper
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/views/purchases/_form.html.erb
<% semantic_form_for :purchase do |f| %>
  <% f.inputs do %>
     <%= f.input :date %>
     <%= f.input :products, :as => :check_boxes %>
  <% end %>
  <%= f.buttons %>
<% end %>

app/views/purchases/edit.html.erb
<% title "Edit Purchase" %>

<%= render :partial => 'form', :locals => { :purchase => @purchase }  %>

<p>
  <%= link_to "Show", @purchase %> |
  <%= link_to "View All", purchases_path %>
</p>

app/views/purchases/index.html.erb
<% title "Purchases" %>

<table>
  <tr>
    <th>Date</th>
  </tr>
  <% for purchase in @purchases %>
    <tr>
      <td><%=h purchase.date %></td>
      <td><%= link_to "Show", purchase %></td>
      <td><%= link_to "Destroy", purchase, :confirm => 'Are you sure?', :method => :delete %></td>
    </tr>
  <% end %>
</table>

<p><%= link_to "New purchase", new_purchase_path %></p>

app/views/purchases/new.html.erb
<% title "New purchase" %>

<%= render :partial => 'form', :locals => { :purchase => @purchase }  %>

<p><%= link_to "Back to List", purchases_path %></p>

app/views/purchases/show.html.erb
<% title "purchase" %>

<p>
  <strong>Date:</strong>
  <%=h @purchase.date %>
</p>

<p>
  <%= link_to "Edit", edit_purchase_path(@purchase) %> |
  <%= link_to "Destroy", @purchase, :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "View All", purchases_path %>
</p>