config/routes.rb
InventoryControl::Application.routes.draw do
  resources :sales
  resources :customers
  resources :products
  resources :brands
  resources :purchases
  match '/:controller(/:action(/:id))'
end

app/models/brand.rb
class Brand < ActiveRecord::Base
  has_many :products
end

app/models/client.rb
class Client < ActiveRecord::Base
  has_many :sales
end

app/models/customer.rb
class Customer < ActiveRecord::Base
  has_many :sales
end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :brand
  
  has_many :sale_orders
  has_many :sales, :through => :sale_orders
  
  has_many :purchase_orders
  has_many :purchases, :through => :purchase_orders

  named_scope :with_brand, { :joins => :brand }
  named_scope :stock_alert, { :conditions => "stock_ammount = stock_minimum" }
end

app/models/purchase.rb
class Purchase < ActiveRecord::Base
  has_many :purchase_orders
  has_many :products, :through => :purchase_orders
end

app/models/purchase_order.rb
class PurchaseOrder < ActiveRecord::Base
  belongs_to :purchase
  belongs_to :product
end

app/models/sale.rb
class Sale < ActiveRecord::Base
  belongs_to :customer
  
  has_many :sale_orders
  has_many :products, :through => :sale_orders
end

app/models/sale_order.rb
class SaleOrder < ActiveRecord::Base
  belongs_to :sale
  belongs_to :product
end

app/controllers/brands_controller.rb
class BrandsController < InheritedResources::Base
  respond_to :html
end

app/controllers/clients_controller.rb
class ClientsController < InheritedResources::Base
  respond_to :html
end

app/controllers/customers_controller.rb
class CustomersController < InheritedResources::Base
  respond_to :html
end

app/controllers/products_controller.rb
class ProductsController < InheritedResources::Base
  respond_to :html

  def index
    index! { @products = Product.with_brand }
  end
end

app/controllers/purchases_controller.rb
class PurchasesController < InheritedResources::Base
  respond_to :html
end

app/controllers/sales_controller.rb
class SalesController < InheritedResources::Base
  respond_to :html
end

app/helpers/analyze_inventory_helper.rb
module AnalyzeInventoryHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    @content_for_title = page_title.to_s
    @show_title = show_title
  end
  
  def show_title?
    @show_title
  end
  
  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end
  
  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/purchases_helper.rb
module PurchasesHelper
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/views/brands/_form.html.erb
<% semantic_form_for @brand do |f| %>
	<%= f.inputs %>
	<%= f.buttons %>
<% end %>

app/views/brands/edit.html.erb
<% title "Edit Brand" %>

<%= render :partial => 'form', :locals => { :brand => @brand } %>

<p>
  <%= link_to "Show", @brand %> |
  <%= link_to "View All", brands_path %>
</p>

app/views/brands/index.html.erb
<% title "Categorias" %>

<p><%= link_to "Nova categoria", new_brand_path %></p>

<table cellspacing="1" class="tablesorter">
<thead>  
  <tr>
    <th>Nome</th>
  </tr>
</thead>
<tbody>
  <% for brand in @brands %>
    <tr>
      <td><%=h brand.name %></td>
      <td><%= link_to "Show", brand %></td>
      <td><%= link_to "Edit", edit_brand_path(brand) %></td>
      <td><%= link_to "Destroy", brand, :confirm => 'Are you sure?', :method => :delete %></td>
    </tr>
  <% end %>
</tbody>
</table>
<br />
<div id="pager" class="pager">
    <form>
        <img src="./images/first.png" class="first" />
        <img src="./images/prev.png" class="prev" />
        <input type="text" class="pagedisplay">
        <img src="./images/next.png" class="next" />
        <img src="./images/last.png" class="last" />
        <select class="pagesize">
            <option selected="selected" value="10">10</option>
            <option value="20">20</option>
            <option value="30">30</option>
            <option value="40">40</option>
        </select>
    </form>
</div>
<p><%= link_to "Voltar", root_path %></p>

app/views/brands/new.html.erb
<% title "New Brand" %>

<%= render :partial => 'form', :locals => { :brand => @brand } %>

<p><%= link_to "Back to List", brands_path %></p>

app/views/brands/show.html.erb
<% title "Brand" %>

<p>
  <strong>Name:</strong>
  <%=h @brand.name %>
</p>

<p>
  <%= link_to "Edit", edit_brand_path(@brand) %> |
  <%= link_to "Destroy", @brand, :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "View All", brands_path %>
</p>

app/views/clients/_form.html.erb
<% semantic_form_for :client do |f| %>
	<%= f.inputs %>
	<%= f.buttons %>
<% end %>

app/views/clients/edit.html.erb
<% title "Edit Client" %>

<%= render :partial => 'form', :locals => { :client => @client } %>

<p>
  <%= link_to "Show", @client %> |
  <%= link_to "View All", clients_path %>
</p>

app/views/clients/index.html.erb
<% title "Clients" %>

<table>
  <tr>
    <th>Name</th>
    <th>Telephone</th>
    <th>Address</th>
    <th>Email</th>
    <th>Rg</th>
  </tr>
  <% for client in @clients %>
    <tr>
      <td><%=h client.name %></td>
      <td><%=h client.telephone %></td>
      <td><%=h client.address %></td>
      <td><%=h client.email %></td>
      <td><%=h client.rg %></td>
      <td><%= link_to "Show", client %></td>
      <td><%= link_to "Edit", edit_client_path(client) %></td>
      <td><%= link_to "Destroy", client, :confirm => 'Are you sure?', :method => :delete %></td>
    </tr>
  <% end %>
</table>

<p><%= link_to "New Client", new_client_path %></p>

app/views/clients/new.html.erb
<% title "New Client" %>

<%= render :partial => 'form', :locals => { :client => @client } %>

<p><%= link_to "Back to List", clients_path %></p>

app/views/clients/show.html.erb
<% title "Client" %>

<p>
  <strong>Name:</strong>
  <%=h @client.name %>
</p>
<p>
  <strong>Telephone:</strong>
  <%=h @client.telephone %>
</p>
<p>
  <strong>Address:</strong>
  <%=h @client.address %>
</p>
<p>
  <strong>Email:</strong>
  <%=h @client.email %>
</p>
<p>
  <strong>Rg:</strong>
  <%=h @client.rg %>
</p>

<p>
  <%= link_to "Edit", edit_client_path(@client) %> |
  <%= link_to "Destroy", @client, :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "View All", clients_path %>
</p>

app/views/customers/_form.html.erb
<% semantic_form_for :customer do |f| %>
	<%= f.inputs %>
	<%= f.buttons %>
<% end %>

app/views/customers/edit.html.erb
<% title "Edit Customer" %>

<%= render :partial => 'form', :locals => { :customer => @customer } %>

<p>
  <%= link_to "Show", @customer %> |
  <%= link_to "View All", customers_path %>
</p>

app/views/customers/index.html.erb
<% title "Customers" %>

<table>
  <tr>
    <th>Name</th>
    <th>Telephone</th>
    <th>Address</th>
    <th>Email</th>
    <th>Rg</th>
  </tr>
  <% for customer in @customers %>
    <tr>
      <td><%=h customer.name %></td>
      <td><%=h customer.telephone %></td>
      <td><%=h customer.address %></td>
      <td><%=h customer.email %></td>
      <td><%=h customer.rg %></td>
      <td><%= link_to "Show", customer %></td>
      <td><%= link_to "Edit", edit_customer_path(customer) %></td>
      <td><%= link_to "Destroy", customer, :confirm => 'Are you sure?', :method => :delete %></td>
    </tr>
  <% end %>
</table>

<p><%= link_to "New Customer", new_customer_path %></p>

app/views/customers/new.html.erb
<% title "New Customer" %>

<%= render :partial => 'form', :locals => { :customer => @customer }  %>

<p><%= link_to "Back to List", customers_path %></p>

app/views/customers/show.html.erb
<% title "Customer" %>

<p>
  <strong>Name:</strong>
  <%=h @customer.name %>
</p>
<p>
  <strong>Telephone:</strong>
  <%=h @customer.telephone %>
</p>
<p>
  <strong>Address:</strong>
  <%=h @customer.address %>
</p>
<p>
  <strong>Email:</strong>
  <%=h @customer.email %>
</p>
<p>
  <strong>Rg:</strong>
  <%=h @customer.rg %>
</p>

<p>
  <%= link_to "Edit", edit_customer_path(@customer) %> |
  <%= link_to "Destroy", @customer, :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "View All", customers_path %>
</p>

app/views/products/_form.html.erb
<% semantic_form_for @product do |form| %>
   <%= form.inputs %>
   <%= form.buttons %>	
<% end %>

app/views/products/edit.html.erb
<% title t :title_edit %>

<%= render :partial => 'form', :locals => { :product => @product } %>

<p>
  <%= link_to "Show", @product %> |
  <%= link_to "View All", products_path %>
</p>

app/views/products/index.html.erb
<% title "Products" %>

<p><%= link_to "Novo produto", new_product_path %></p>

<table cellspacing="1" class="tablesorter">
  <thead>  
    <tr>
      <th>Nome</th>
      <th>Categoria</th>
      <th>Preço de compra</th>
      <th>Quantidade estocada</th>
      <th>Quantidade mínima</th>
    </tr>
  </thead>
  <tbody>
    <% for product in @products %>
      <tr <% if product.stock_ammount <= product.stock_minimum %> class="stock_minimum" <% end %>>
        <td><%=h product.name %></td>
        <td><%=h product.brand.name %></td>
        <td><%=h product.bought_price %></td>
        <td><%=h product.stock_ammount %></td>
        <td><%=h product.stock_minimum %></td>
        <td><%= link_to image_tag("show.png", :title => "Visualizar"), product %></td>
        <td><%= link_to image_tag("edit.png", :title => "Editar"), edit_product_path(product) %></td>
        <td><%= link_to image_tag("delete.png"), product, :confirm => 'Você deseja remover?', :method => :delete %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br />
<div id="pager" class="pager">
    <form>
        <img src="./images/first.png" class="first" />
        <img src="./images/prev.png" class="prev" />
        <input type="text" class="pagedisplay">
        <img src="./images/next.png" class="next" />
        <img src="./images/last.png" class="last" />
        <select class="pagesize">
            <option selected="selected" value="10">10</option>
            <option value="20">20</option>
            <option value="30">30</option>
            <option value="40">40</option>
        </select>
    </form>
</div>
<p><%= link_to "Voltar", root_path %></p>

app/views/products/new.html.erb
<% title "New Product" %>

<%= render :partial => 'form', :locals => { :product => @product } %>

<p><%= link_to "Voltar", products_path %></p>

app/views/products/show.html.erb
<% title "Product" %>

<p>
  <strong>Name:</strong>
  <%=h @product.name %>
</p>
<p>
  <strong>Brand:</strong>
  <%=h @product.brand_id %>
</p>
<p>
  <strong>Preço de compra:</strong>
  <%=h @product.bought_price %>
</p>
<p>
  <strong>Quantidade estocada:</strong>
  <%=h @product.stock_ammount %>
</p>
<p>
<strong>Quantidade mínima:</strong>
  <%=h @product.stock_minimum %>
</p>

<p>
  <%= link_to "Edit", edit_product_path(@product) %> |
  <%= link_to "Destroy", @product, :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "View All", products_path %>
</p>

app/views/sales/_form.html.erb
<% semantic_form_for :sale do |f| %>
  <% f.inputs do %>
     <%= f.input :date %>
	 <%= f.input :customer %>
     <%= f.input :products, :as => :check_boxes %>
  <% end %>
  <%= f.buttons %>
<% end %>

app/views/sales/edit.html.erb
<% title "Edit Sale" %>

<%= render :partial => 'form', :locals => { :sale => @sale } %>

<p>
  <%= link_to "Show", @sale %> |
  <%= link_to "View All", sales_path %>
</p>

app/views/sales/index.html.erb
<% title "Sales" %>

<table>
  <tr>
    <th>Customer</th>
    <th>Date</th>
  </tr>
  <% for sale in @sales %>
    <tr>
      <td><%=h sale.customer_id %></td>
      <td><%=h sale.date %></td>
      <td><%= link_to "Show", sale %></td>
      <td><%= link_to "Edit", edit_sale_path(sale) %></td>
      <td><%= link_to "Destroy", sale, :confirm => 'Are you sure?', :method => :delete %></td>
    </tr>
  <% end %>
</table>

<p><%= link_to "New Sale", new_sale_path %></p>

app/views/sales/new.html.erb
<% title "New Sale" %>

<%= render :partial => 'form', :locals => { :sale => @sale } %>

<p><%= link_to "Back to List", sales_path %></p>

app/views/sales/show.html.erb
<% title "Sale" %>

<p>
  <strong>Customer:</strong>
  <%=h @sale.customer_id %>
</p>
<p>
  <strong>Date:</strong>
  <%=h @sale.date %>
</p>

<p>
  <%= link_to "Edit", edit_sale_path(@sale) %> |
  <%= link_to "Destroy", @sale, :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "View All", sales_path %>
</p>